### ISSUE TITLE
Unexpected token error when trying to import 'Ws'

### ISSUE THREAD

**Issue by jaymeh** [adonisjs/adonis-websocket-client#57]
Hi,

I am trying to run some client side sockets in electron to connect to an Adonis dashboard and backend. I'm getting the following error when trying to import the "Ws" package from node modules. Thinking it may have something to do with my project configuration but couldn't see anything that stood out. 

```/node_modules/@adonisjs/websocket-client/dist/Ws.es.js:2507
  export default index;
  ^^^^^^
  
  SyntaxError: Unexpected token export
      at createScript (vm.js:80:10)
      at Object.runInThisContext (vm.js:139:10)
      at Module._compile (module.js:606:28)
      at Object.Module._extensions..js (module.js:653:10)
      at Module.load (module.js:561:32)
      at tryModuleLoad (module.js:504:12)
      at Function.Module._load (module.js:496:3)
      at Module.require (module.js:586:17)
      at require (internal/module.js:11:18)
      at eval (webpack:///external_%22@adonisjs/websocket-client%22?:1:18)
```

My repo is here in case you may need to check something in my app configuration https://github.com/jaymeh/time-tracking-electron. 

I am including the package in "**src/main/index.js**".

Thanks!

**Comment by jaymeh** [comment]
Seemed to have been an issue with my project and Babel however the Connection expects a window object which will never be set within an Electron backend. Closing this issue now.

Thanks
